name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 black
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff .
    
    - name: Test Python compilation
      run: |
        python -m py_compile *.py
    
    - name: Run basic import tests
      run: |
        python -c "
        import sys
        import os
        sys.path.insert(0, os.getcwd())
        
        modules = [
            'convolution', 'dsu', 'fenwicktree', 'fps', 'lazysegtree',
            'acl_math', 'maxflow', 'mincostflow', 'prime_fact', 'scc',
            'segtree', 'string', 'two_sat'
        ]
        
        for module in modules:
            try:
                __import__(module)
                print(f'✓ {module} imported successfully')
            except ImportError as e:
                print(f'✗ Failed to import {module}: {e}')
                sys.exit(1)
        
        print('All modules imported successfully!')
        "

  pypy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PyPy
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy-3.9'
    
    - name: Test PyPy compilation
      run: |
        python -m py_compile *.py
    
    - name: Run PyPy import tests
      run: |
        python -c "
        import sys
        import os
        sys.path.insert(0, os.getcwd())
        
        modules = [
            'convolution', 'dsu', 'fenwicktree', 'fps', 'lazysegtree',
            'acl_math', 'maxflow', 'mincostflow', 'prime_fact', 'scc',
            'segtree', 'string', 'two_sat'
        ]
        
        for module in modules:
            try:
                __import__(module)
                print(f'✓ {module} imported successfully on PyPy')
            except ImportError as e:
                print(f'✗ Failed to import {module} on PyPy: {e}')
                sys.exit(1)
        
        print('All modules imported successfully on PyPy!')
        "