name: Auto Format

on:
  pull_request:
    branches: [ master, main ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install black
        run: pip install black
      - name: Format code
        run: black .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format code"
          branch: ${{ github.head_ref }}
